# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from briosa.core.v1alpha1 import discovery_pb2 as briosa_dot_core_dot_v1alpha1_dot_discovery__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in briosa/core/v1alpha1/discovery_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiscoveryServiceStub(object):
    """Provides low-sensitivity server identity and exact-target capability metadata.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerInfo = channel.unary_unary(
                '/briosa.core.v1alpha1.DiscoveryService/GetServerInfo',
                request_serializer=briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.GetServerInfoRequest.SerializeToString,
                response_deserializer=briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.GetServerInfoResponse.FromString,
                _registered_method=True)
        self.ListCapabilities = channel.unary_unary(
                '/briosa.core.v1alpha1.DiscoveryService/ListCapabilities',
                request_serializer=briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.ListCapabilitiesRequest.SerializeToString,
                response_deserializer=briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.ListCapabilitiesResponse.FromString,
                _registered_method=True)


class DiscoveryServiceServicer(object):
    """Provides low-sensitivity server identity and exact-target capability metadata.
    """

    def GetServerInfo(self, request, context):
        """Returns build coordinates and a safe current runtime summary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCapabilities(self, request, context):
        """Lists only operations in this build's reviewed command catalog.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.GetServerInfoRequest.FromString,
                    response_serializer=briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.GetServerInfoResponse.SerializeToString,
            ),
            'ListCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCapabilities,
                    request_deserializer=briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.ListCapabilitiesRequest.FromString,
                    response_serializer=briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.ListCapabilitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'briosa.core.v1alpha1.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('briosa.core.v1alpha1.DiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """Provides low-sensitivity server identity and exact-target capability metadata.
    """

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.core.v1alpha1.DiscoveryService/GetServerInfo',
            briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.GetServerInfoRequest.SerializeToString,
            briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.GetServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.core.v1alpha1.DiscoveryService/ListCapabilities',
            briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.ListCapabilitiesRequest.SerializeToString,
            briosa_dot_core_dot_v1alpha1_dot_discovery__pb2.ListCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
