# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from briosa import analysis_operations_pb2 as briosa_dot_analysis__operations__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in briosa/analysis_operations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisOperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIThCollectionName = channel.unary_unary(
                '/briosa.AnalysisOperations/GetIThCollectionName',
                request_serializer=briosa_dot_analysis__operations__pb2.GetIThCollectionNameRequest.SerializeToString,
                response_deserializer=briosa_dot_analysis__operations__pb2.GetIThCollectionNameResult.FromString,
                _registered_method=True)
        self.GetNumberOfCollections = channel.unary_unary(
                '/briosa.AnalysisOperations/GetNumberOfCollections',
                request_serializer=briosa_dot_analysis__operations__pb2.GetNumberOfCollectionsRequest.SerializeToString,
                response_deserializer=briosa_dot_analysis__operations__pb2.GetNumberOfCollectionsResult.FromString,
                _registered_method=True)


class AnalysisOperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIThCollectionName(self, request, context):
        """Executes the "Get i-th Collection Name" MP command.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNumberOfCollections(self, request, context):
        """Executes the "Get Number of Collections" MP command.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIThCollectionName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIThCollectionName,
                    request_deserializer=briosa_dot_analysis__operations__pb2.GetIThCollectionNameRequest.FromString,
                    response_serializer=briosa_dot_analysis__operations__pb2.GetIThCollectionNameResult.SerializeToString,
            ),
            'GetNumberOfCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNumberOfCollections,
                    request_deserializer=briosa_dot_analysis__operations__pb2.GetNumberOfCollectionsRequest.FromString,
                    response_serializer=briosa_dot_analysis__operations__pb2.GetNumberOfCollectionsResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'briosa.AnalysisOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('briosa.AnalysisOperations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisOperations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIThCollectionName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.AnalysisOperations/GetIThCollectionName',
            briosa_dot_analysis__operations__pb2.GetIThCollectionNameRequest.SerializeToString,
            briosa_dot_analysis__operations__pb2.GetIThCollectionNameResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNumberOfCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.AnalysisOperations/GetNumberOfCollections',
            briosa_dot_analysis__operations__pb2.GetNumberOfCollectionsRequest.SerializeToString,
            briosa_dot_analysis__operations__pb2.GetNumberOfCollectionsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
