# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: briosa/analysis_operations.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'briosa/analysis_operations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from briosa import operation_outcomes_pb2 as briosa_dot_operation__outcomes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n briosa/analysis_operations.proto\x12\x06\x62riosa\x1a\x1f\x62riosa/operation_outcomes.proto\"Q\n\x1bGetIThCollectionNameRequest\x12\x1d\n\x10\x63ollection_index\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\x13\n\x11_collection_index\"|\n\x1aGetIThCollectionNameResult\x12\x1b\n\x0eresultant_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12.\n\texecution\x18\xe8\x07 \x01(\x0b\x32\x1a.briosa.MpExecutionDetailsB\x11\n\x0f_resultant_name\"\x1f\n\x1dGetNumberOfCollectionsRequest\"x\n\x1cGetNumberOfCollectionsResult\x12\x18\n\x0btotal_count\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12.\n\texecution\x18\xe8\x07 \x01(\x0b\x32\x1a.briosa.MpExecutionDetailsB\x0e\n\x0c_total_count2\xdc\x01\n\x12\x41nalysisOperations\x12_\n\x14GetIThCollectionName\x12#.briosa.GetIThCollectionNameRequest\x1a\".briosa.GetIThCollectionNameResult\x12\x65\n\x16GetNumberOfCollections\x12%.briosa.GetNumberOfCollectionsRequest\x1a$.briosa.GetNumberOfCollectionsResultB\t\xaa\x02\x06\x42riosab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'briosa.analysis_operations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\006Briosa'
  _globals['_GETITHCOLLECTIONNAMEREQUEST']._serialized_start=77
  _globals['_GETITHCOLLECTIONNAMEREQUEST']._serialized_end=158
  _globals['_GETITHCOLLECTIONNAMERESULT']._serialized_start=160
  _globals['_GETITHCOLLECTIONNAMERESULT']._serialized_end=284
  _globals['_GETNUMBEROFCOLLECTIONSREQUEST']._serialized_start=286
  _globals['_GETNUMBEROFCOLLECTIONSREQUEST']._serialized_end=317
  _globals['_GETNUMBEROFCOLLECTIONSRESULT']._serialized_start=319
  _globals['_GETNUMBEROFCOLLECTIONSRESULT']._serialized_end=439
  _globals['_ANALYSISOPERATIONS']._serialized_start=442
  _globals['_ANALYSISOPERATIONS']._serialized_end=662
# @@protoc_insertion_point(module_scope)
