# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: briosa/construction_operations.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'briosa/construction_operations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from briosa import operation_outcomes_pb2 as briosa_dot_operation__outcomes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$briosa/construction_operations.proto\x12\x06\x62riosa\x1a\x1f\x62riosa/operation_outcomes.proto\" \n\x1eGetActiveCollectionNameRequest\"\xa3\x01\n\x1dGetActiveCollectionNameResult\x12-\n currently_active_collection_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12.\n\texecution\x18\xe8\x07 \x01(\x0b\x32\x1a.briosa.MpExecutionDetailsB#\n!_currently_active_collection_name2\x82\x01\n\x16\x43onstructionOperations\x12h\n\x17GetActiveCollectionName\x12&.briosa.GetActiveCollectionNameRequest\x1a%.briosa.GetActiveCollectionNameResultB\t\xaa\x02\x06\x42riosab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'briosa.construction_operations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\006Briosa'
  _globals['_GETACTIVECOLLECTIONNAMEREQUEST']._serialized_start=81
  _globals['_GETACTIVECOLLECTIONNAMEREQUEST']._serialized_end=113
  _globals['_GETACTIVECOLLECTIONNAMERESULT']._serialized_start=116
  _globals['_GETACTIVECOLLECTIONNAMERESULT']._serialized_end=279
  _globals['_CONSTRUCTIONOPERATIONS']._serialized_start=282
  _globals['_CONSTRUCTIONOPERATIONS']._serialized_end=412
# @@protoc_insertion_point(module_scope)
