# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from briosa import event_operations_pb2 as briosa_dot_event__operations__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in briosa/event_operations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventOperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteEvent = channel.unary_unary(
                '/briosa.EventOperations/DeleteEvent',
                request_serializer=briosa_dot_event__operations__pb2.DeleteEventRequest.SerializeToString,
                response_deserializer=briosa_dot_event__operations__pb2.DeleteEventResult.FromString,
                _registered_method=True)
        self.ExportEventRefList = channel.unary_unary(
                '/briosa.EventOperations/ExportEventRefList',
                request_serializer=briosa_dot_event__operations__pb2.ExportEventRefListRequest.SerializeToString,
                response_deserializer=briosa_dot_event__operations__pb2.ExportEventRefListResult.FromString,
                _registered_method=True)
        self.GetIthEventFromEventRefList = channel.unary_unary(
                '/briosa.EventOperations/GetIthEventFromEventRefList',
                request_serializer=briosa_dot_event__operations__pb2.GetIthEventFromEventRefListRequest.SerializeToString,
                response_deserializer=briosa_dot_event__operations__pb2.GetIthEventFromEventRefListResult.FromString,
                _registered_method=True)
        self.GetNumberOfEventsInEventRefList = channel.unary_unary(
                '/briosa.EventOperations/GetNumberOfEventsInEventRefList',
                request_serializer=briosa_dot_event__operations__pb2.GetNumberOfEventsInEventRefListRequest.SerializeToString,
                response_deserializer=briosa_dot_event__operations__pb2.GetNumberOfEventsInEventRefListResult.FromString,
                _registered_method=True)
        self.RenameEvent = channel.unary_unary(
                '/briosa.EventOperations/RenameEvent',
                request_serializer=briosa_dot_event__operations__pb2.RenameEventRequest.SerializeToString,
                response_deserializer=briosa_dot_event__operations__pb2.RenameEventResult.FromString,
                _registered_method=True)


class EventOperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeleteEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportEventRefList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIthEventFromEventRefList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNumberOfEventsInEventRefList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEvent,
                    request_deserializer=briosa_dot_event__operations__pb2.DeleteEventRequest.FromString,
                    response_serializer=briosa_dot_event__operations__pb2.DeleteEventResult.SerializeToString,
            ),
            'ExportEventRefList': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportEventRefList,
                    request_deserializer=briosa_dot_event__operations__pb2.ExportEventRefListRequest.FromString,
                    response_serializer=briosa_dot_event__operations__pb2.ExportEventRefListResult.SerializeToString,
            ),
            'GetIthEventFromEventRefList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIthEventFromEventRefList,
                    request_deserializer=briosa_dot_event__operations__pb2.GetIthEventFromEventRefListRequest.FromString,
                    response_serializer=briosa_dot_event__operations__pb2.GetIthEventFromEventRefListResult.SerializeToString,
            ),
            'GetNumberOfEventsInEventRefList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNumberOfEventsInEventRefList,
                    request_deserializer=briosa_dot_event__operations__pb2.GetNumberOfEventsInEventRefListRequest.FromString,
                    response_serializer=briosa_dot_event__operations__pb2.GetNumberOfEventsInEventRefListResult.SerializeToString,
            ),
            'RenameEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameEvent,
                    request_deserializer=briosa_dot_event__operations__pb2.RenameEventRequest.FromString,
                    response_serializer=briosa_dot_event__operations__pb2.RenameEventResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'briosa.EventOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('briosa.EventOperations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventOperations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeleteEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.EventOperations/DeleteEvent',
            briosa_dot_event__operations__pb2.DeleteEventRequest.SerializeToString,
            briosa_dot_event__operations__pb2.DeleteEventResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportEventRefList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.EventOperations/ExportEventRefList',
            briosa_dot_event__operations__pb2.ExportEventRefListRequest.SerializeToString,
            briosa_dot_event__operations__pb2.ExportEventRefListResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIthEventFromEventRefList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.EventOperations/GetIthEventFromEventRefList',
            briosa_dot_event__operations__pb2.GetIthEventFromEventRefListRequest.SerializeToString,
            briosa_dot_event__operations__pb2.GetIthEventFromEventRefListResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNumberOfEventsInEventRefList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.EventOperations/GetNumberOfEventsInEventRefList',
            briosa_dot_event__operations__pb2.GetNumberOfEventsInEventRefListRequest.SerializeToString,
            briosa_dot_event__operations__pb2.GetNumberOfEventsInEventRefListResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenameEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.EventOperations/RenameEvent',
            briosa_dot_event__operations__pb2.RenameEventRequest.SerializeToString,
            briosa_dot_event__operations__pb2.RenameEventResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
