# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from briosa import robot_calibration_appliance_node_operations_pb2 as briosa_dot_robot__calibration__appliance__node__operations__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in briosa/robot_calibration_appliance_node_operations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotCalibrationApplianceNodeOperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetCalibrationApplianceNodeMeasurementOffsetTransform = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeMeasurementOffsetTransform',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementOffsetTransformRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementOffsetTransformResult.FromString,
                _registered_method=True)
        self.EnableDisableCalibrationApplianceNodeTrapManager = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/EnableDisableCalibrationApplianceNodeTrapManager',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeTrapManagerRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeTrapManagerResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeIntegerValue = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeIntegerValue',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeIntegerValueRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeIntegerValueResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeTrappingNodeId = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeTrappingNodeId',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeTrappingNodeIdRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeTrappingNodeIdResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeCalibrationApplianceIpAddress = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeCalibrationApplianceIpAddress',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeCalibrationApplianceIpAddressRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeCalibrationApplianceIpAddressResult.FromString,
                _registered_method=True)
        self.GetCalibrationApplianceNodeRealValue = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/GetCalibrationApplianceNodeRealValue',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeRealValueRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeRealValueResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeMeasurementFrame = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeMeasurementFrame',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementFrameRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementFrameResult.FromString,
                _registered_method=True)
        self.SkipCalibrationApplianceNodeMeasurement = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SkipCalibrationApplianceNodeMeasurement',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SkipCalibrationApplianceNodeMeasurementRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SkipCalibrationApplianceNodeMeasurementResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeMeasurementPointGroup = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeMeasurementPointGroup',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementPointGroupRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementPointGroupResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeData = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeData',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDataRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDataResult.FromString,
                _registered_method=True)
        self.ConnectDisconnectCalibrationApplianceNode = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/ConnectDisconnectCalibrationApplianceNode',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.ConnectDisconnectCalibrationApplianceNodeRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.ConnectDisconnectCalibrationApplianceNodeResult.FromString,
                _registered_method=True)
        self.GetCalibrationApplianceNodeStatus = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/GetCalibrationApplianceNodeStatus',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeStatusRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeStatusResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeRealValue = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeRealValue',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeRealValueRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeRealValueResult.FromString,
                _registered_method=True)
        self.DeleteCalibrationApplianceNode = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/DeleteCalibrationApplianceNode',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.DeleteCalibrationApplianceNodeRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.DeleteCalibrationApplianceNodeResult.FromString,
                _registered_method=True)
        self.UpdateCalibrationApplianceNodeDisplayRobotJoints = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/UpdateCalibrationApplianceNodeDisplayRobotJoints',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.UpdateCalibrationApplianceNodeDisplayRobotJointsRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.UpdateCalibrationApplianceNodeDisplayRobotJointsResult.FromString,
                _registered_method=True)
        self.GetCalibrationApplianceNodeData = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/GetCalibrationApplianceNodeData',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeDataRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeDataResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeInstrument = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeInstrument',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeMeasurementProfile = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeMeasurementProfile',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementProfileRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementProfileResult.FromString,
                _registered_method=True)
        self.AddCalibrationApplianceNode = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/AddCalibrationApplianceNode',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.AddCalibrationApplianceNodeRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.AddCalibrationApplianceNodeResult.FromString,
                _registered_method=True)
        self.GetCalibrationApplianceNodeIntegerValue = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/GetCalibrationApplianceNodeIntegerValue',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeIntegerValueRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeIntegerValueResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeInstrumentDwellTime = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeInstrumentDwellTime',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentDwellTimeRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentDwellTimeResult.FromString,
                _registered_method=True)
        self.EnableDisableCalibrationApplianceNodeInstrumentAutoPoint = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/EnableDisableCalibrationApplianceNodeInstrumentAutoPoint',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeInstrumentAutoPointRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeInstrumentAutoPointResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeMeasurementTarget = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeMeasurementTarget',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementTargetRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementTargetResult.FromString,
                _registered_method=True)
        self.ClearCalibrationApplianceNodeTrapManagerRequests = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/ClearCalibrationApplianceNodeTrapManagerRequests',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.ClearCalibrationApplianceNodeTrapManagerRequestsRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.ClearCalibrationApplianceNodeTrapManagerRequestsResult.FromString,
                _registered_method=True)
        self.SetCalibrationApplianceNodeDisplayRobot = channel.unary_unary(
                '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeDisplayRobot',
                request_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDisplayRobotRequest.SerializeToString,
                response_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDisplayRobotResult.FromString,
                _registered_method=True)


class RobotCalibrationApplianceNodeOperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetCalibrationApplianceNodeMeasurementOffsetTransform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableDisableCalibrationApplianceNodeTrapManager(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeIntegerValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeTrappingNodeId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeCalibrationApplianceIpAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCalibrationApplianceNodeRealValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeMeasurementFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SkipCalibrationApplianceNodeMeasurement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeMeasurementPointGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectDisconnectCalibrationApplianceNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCalibrationApplianceNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeRealValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCalibrationApplianceNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCalibrationApplianceNodeDisplayRobotJoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCalibrationApplianceNodeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeInstrument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeMeasurementProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCalibrationApplianceNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCalibrationApplianceNodeIntegerValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeInstrumentDwellTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableDisableCalibrationApplianceNodeInstrumentAutoPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeMeasurementTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCalibrationApplianceNodeTrapManagerRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCalibrationApplianceNodeDisplayRobot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotCalibrationApplianceNodeOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetCalibrationApplianceNodeMeasurementOffsetTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeMeasurementOffsetTransform,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementOffsetTransformRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementOffsetTransformResult.SerializeToString,
            ),
            'EnableDisableCalibrationApplianceNodeTrapManager': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableDisableCalibrationApplianceNodeTrapManager,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeTrapManagerRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeTrapManagerResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeIntegerValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeIntegerValue,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeIntegerValueRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeIntegerValueResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeTrappingNodeId': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeTrappingNodeId,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeTrappingNodeIdRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeTrappingNodeIdResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeCalibrationApplianceIpAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeCalibrationApplianceIpAddress,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeCalibrationApplianceIpAddressRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeCalibrationApplianceIpAddressResult.SerializeToString,
            ),
            'GetCalibrationApplianceNodeRealValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCalibrationApplianceNodeRealValue,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeRealValueRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeRealValueResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeMeasurementFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeMeasurementFrame,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementFrameRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementFrameResult.SerializeToString,
            ),
            'SkipCalibrationApplianceNodeMeasurement': grpc.unary_unary_rpc_method_handler(
                    servicer.SkipCalibrationApplianceNodeMeasurement,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SkipCalibrationApplianceNodeMeasurementRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SkipCalibrationApplianceNodeMeasurementResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeMeasurementPointGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeMeasurementPointGroup,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementPointGroupRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementPointGroupResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeData': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeData,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDataRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDataResult.SerializeToString,
            ),
            'ConnectDisconnectCalibrationApplianceNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectDisconnectCalibrationApplianceNode,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.ConnectDisconnectCalibrationApplianceNodeRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.ConnectDisconnectCalibrationApplianceNodeResult.SerializeToString,
            ),
            'GetCalibrationApplianceNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCalibrationApplianceNodeStatus,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeStatusRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeStatusResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeRealValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeRealValue,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeRealValueRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeRealValueResult.SerializeToString,
            ),
            'DeleteCalibrationApplianceNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCalibrationApplianceNode,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.DeleteCalibrationApplianceNodeRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.DeleteCalibrationApplianceNodeResult.SerializeToString,
            ),
            'UpdateCalibrationApplianceNodeDisplayRobotJoints': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCalibrationApplianceNodeDisplayRobotJoints,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.UpdateCalibrationApplianceNodeDisplayRobotJointsRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.UpdateCalibrationApplianceNodeDisplayRobotJointsResult.SerializeToString,
            ),
            'GetCalibrationApplianceNodeData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCalibrationApplianceNodeData,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeDataRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeDataResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeInstrument': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeInstrument,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeMeasurementProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeMeasurementProfile,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementProfileRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementProfileResult.SerializeToString,
            ),
            'AddCalibrationApplianceNode': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCalibrationApplianceNode,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.AddCalibrationApplianceNodeRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.AddCalibrationApplianceNodeResult.SerializeToString,
            ),
            'GetCalibrationApplianceNodeIntegerValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCalibrationApplianceNodeIntegerValue,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeIntegerValueRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeIntegerValueResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeInstrumentDwellTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeInstrumentDwellTime,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentDwellTimeRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentDwellTimeResult.SerializeToString,
            ),
            'EnableDisableCalibrationApplianceNodeInstrumentAutoPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableDisableCalibrationApplianceNodeInstrumentAutoPoint,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeInstrumentAutoPointRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeInstrumentAutoPointResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeMeasurementTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeMeasurementTarget,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementTargetRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementTargetResult.SerializeToString,
            ),
            'ClearCalibrationApplianceNodeTrapManagerRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCalibrationApplianceNodeTrapManagerRequests,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.ClearCalibrationApplianceNodeTrapManagerRequestsRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.ClearCalibrationApplianceNodeTrapManagerRequestsResult.SerializeToString,
            ),
            'SetCalibrationApplianceNodeDisplayRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCalibrationApplianceNodeDisplayRobot,
                    request_deserializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDisplayRobotRequest.FromString,
                    response_serializer=briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDisplayRobotResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'briosa.RobotCalibrationApplianceNodeOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('briosa.RobotCalibrationApplianceNodeOperations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotCalibrationApplianceNodeOperations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetCalibrationApplianceNodeMeasurementOffsetTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeMeasurementOffsetTransform',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementOffsetTransformRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementOffsetTransformResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableDisableCalibrationApplianceNodeTrapManager(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/EnableDisableCalibrationApplianceNodeTrapManager',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeTrapManagerRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeTrapManagerResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeIntegerValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeIntegerValue',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeIntegerValueRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeIntegerValueResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeTrappingNodeId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeTrappingNodeId',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeTrappingNodeIdRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeTrappingNodeIdResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeCalibrationApplianceIpAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeCalibrationApplianceIpAddress',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeCalibrationApplianceIpAddressRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeCalibrationApplianceIpAddressResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCalibrationApplianceNodeRealValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/GetCalibrationApplianceNodeRealValue',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeRealValueRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeRealValueResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeMeasurementFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeMeasurementFrame',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementFrameRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementFrameResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SkipCalibrationApplianceNodeMeasurement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SkipCalibrationApplianceNodeMeasurement',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SkipCalibrationApplianceNodeMeasurementRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SkipCalibrationApplianceNodeMeasurementResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeMeasurementPointGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeMeasurementPointGroup',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementPointGroupRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementPointGroupResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeData',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDataRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDataResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectDisconnectCalibrationApplianceNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/ConnectDisconnectCalibrationApplianceNode',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.ConnectDisconnectCalibrationApplianceNodeRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.ConnectDisconnectCalibrationApplianceNodeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCalibrationApplianceNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/GetCalibrationApplianceNodeStatus',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeStatusRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeStatusResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeRealValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeRealValue',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeRealValueRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeRealValueResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCalibrationApplianceNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/DeleteCalibrationApplianceNode',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.DeleteCalibrationApplianceNodeRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.DeleteCalibrationApplianceNodeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCalibrationApplianceNodeDisplayRobotJoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/UpdateCalibrationApplianceNodeDisplayRobotJoints',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.UpdateCalibrationApplianceNodeDisplayRobotJointsRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.UpdateCalibrationApplianceNodeDisplayRobotJointsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCalibrationApplianceNodeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/GetCalibrationApplianceNodeData',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeDataRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeDataResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeInstrument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeInstrument',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeMeasurementProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeMeasurementProfile',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementProfileRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementProfileResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCalibrationApplianceNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/AddCalibrationApplianceNode',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.AddCalibrationApplianceNodeRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.AddCalibrationApplianceNodeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCalibrationApplianceNodeIntegerValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/GetCalibrationApplianceNodeIntegerValue',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeIntegerValueRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.GetCalibrationApplianceNodeIntegerValueResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeInstrumentDwellTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeInstrumentDwellTime',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentDwellTimeRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeInstrumentDwellTimeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableDisableCalibrationApplianceNodeInstrumentAutoPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/EnableDisableCalibrationApplianceNodeInstrumentAutoPoint',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeInstrumentAutoPointRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.EnableDisableCalibrationApplianceNodeInstrumentAutoPointResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeMeasurementTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeMeasurementTarget',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementTargetRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeMeasurementTargetResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCalibrationApplianceNodeTrapManagerRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/ClearCalibrationApplianceNodeTrapManagerRequests',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.ClearCalibrationApplianceNodeTrapManagerRequestsRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.ClearCalibrationApplianceNodeTrapManagerRequestsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCalibrationApplianceNodeDisplayRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.RobotCalibrationApplianceNodeOperations/SetCalibrationApplianceNodeDisplayRobot',
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDisplayRobotRequest.SerializeToString,
            briosa_dot_robot__calibration__appliance__node__operations__pb2.SetCalibrationApplianceNodeDisplayRobotResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
