# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: briosa/spatial_analyzer_values.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'briosa/spatial_analyzer_values.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$briosa/spatial_analyzer_values.proto\x12\x06\x62riosa\"\x9b\x01\n\x14\x43ollectionObjectName\x12\x1c\n\x0f\x63ollection_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bobject_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\'\n\x0bobject_type\x18\x03 \x01(\x0e\x32\x12.briosa.ObjectTypeB\x12\n\x10_collection_nameB\x0e\n\x0c_object_name*\xd9\x05\n\nObjectType\x12\x1b\n\x17OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fOBJECT_TYPE_ANY\x10\x01\x12\x18\n\x14OBJECT_TYPE_B_SPLINE\x10\x02\x12\x16\n\x12OBJECT_TYPE_CIRCLE\x10\x03\x12\x15\n\x11OBJECT_TYPE_CLOUD\x10\x04\x12\x1e\n\x1aOBJECT_TYPE_ENHANCED_CLOUD\x10\x05\x12!\n\x1dOBJECT_TYPE_SCAN_STRIPE_CLOUD\x10\x06\x12#\n\x1fOBJECT_TYPE_CROSS_SECTION_CLOUD\x10\x07\x12\x14\n\x10OBJECT_TYPE_CONE\x10\x08\x12\x18\n\x14OBJECT_TYPE_CYLINDER\x10\t\x12\x15\n\x11OBJECT_TYPE_DATUM\x10\n\x12\x17\n\x13OBJECT_TYPE_ELLIPSE\x10\x0b\x12\x15\n\x11OBJECT_TYPE_FRAME\x10\x0c\x12\x19\n\x15OBJECT_TYPE_FRAME_SET\x10\r\x12\x14\n\x10OBJECT_TYPE_LINE\x10\x0e\x12\x1a\n\x16OBJECT_TYPE_PARABOLOID\x10\x0f\x12\x19\n\x15OBJECT_TYPE_PERIMETER\x10\x10\x12\x15\n\x11OBJECT_TYPE_PLANE\x10\x11\x12\x1b\n\x17OBJECT_TYPE_POINT_GROUP\x10\x12\x12\x19\n\x15OBJECT_TYPE_POINT_SET\x10\x13\x12\x1c\n\x18OBJECT_TYPE_POLY_SURFACE\x10\x14\x12 \n\x1cOBJECT_TYPE_SCAN_STRIPE_MESH\x10\x15\x12\x14\n\x10OBJECT_TYPE_SLOT\x10\x16\x12\x16\n\x12OBJECT_TYPE_SPHERE\x10\x17\x12\x17\n\x13OBJECT_TYPE_SURFACE\x10\x18\x12\x15\n\x11OBJECT_TYPE_TORUS\x10\x19\x12\x1c\n\x18OBJECT_TYPE_VECTOR_GROUP\x10\x1a\x42\t\xaa\x02\x06\x42riosab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'briosa.spatial_analyzer_values_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\006Briosa'
  _globals['_OBJECTTYPE']._serialized_start=207
  _globals['_OBJECTTYPE']._serialized_end=936
  _globals['_COLLECTIONOBJECTNAME']._serialized_start=49
  _globals['_COLLECTIONOBJECTNAME']._serialized_end=204
# @@protoc_insertion_point(module_scope)
