# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from briosa import view_control_pb2 as briosa_dot_view__control__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in briosa/view_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ViewControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AutoScale = channel.unary_unary(
                '/briosa.ViewControl/AutoScale',
                request_serializer=briosa_dot_view__control__pb2.AutoScaleRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.AutoScaleResult.FromString,
                _registered_method=True)
        self.CenterGraphicsAboutObjects = channel.unary_unary(
                '/briosa.ViewControl/CenterGraphicsAboutObjects',
                request_serializer=briosa_dot_view__control__pb2.CenterGraphicsAboutObjectsRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.CenterGraphicsAboutObjectsResult.FromString,
                _registered_method=True)
        self.CenterGraphicsAboutPoint = channel.unary_unary(
                '/briosa.ViewControl/CenterGraphicsAboutPoint',
                request_serializer=briosa_dot_view__control__pb2.CenterGraphicsAboutPointRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.CenterGraphicsAboutPointResult.FromString,
                _registered_method=True)
        self.DefinePointOfView = channel.unary_unary(
                '/briosa.ViewControl/DefinePointOfView',
                request_serializer=briosa_dot_view__control__pb2.DefinePointOfViewRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.DefinePointOfViewResult.FromString,
                _registered_method=True)
        self.GetActiveClippingPlanes = channel.unary_unary(
                '/briosa.ViewControl/GetActiveClippingPlanes',
                request_serializer=briosa_dot_view__control__pb2.GetActiveClippingPlanesRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.GetActiveClippingPlanesResult.FromString,
                _registered_method=True)
        self.GetPointOfViewParameters = channel.unary_unary(
                '/briosa.ViewControl/GetPointOfViewParameters',
                request_serializer=briosa_dot_view__control__pb2.GetPointOfViewParametersRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.GetPointOfViewParametersResult.FromString,
                _registered_method=True)
        self.HideAllCalloutViews = channel.unary_unary(
                '/briosa.ViewControl/HideAllCalloutViews',
                request_serializer=briosa_dot_view__control__pb2.HideAllCalloutViewsRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.HideAllCalloutViewsResult.FromString,
                _registered_method=True)
        self.HideObjects = channel.unary_unary(
                '/briosa.ViewControl/HideObjects',
                request_serializer=briosa_dot_view__control__pb2.HideObjectsRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.HideObjectsResult.FromString,
                _registered_method=True)
        self.HighlightObjects = channel.unary_unary(
                '/briosa.ViewControl/HighlightObjects',
                request_serializer=briosa_dot_view__control__pb2.HighlightObjectsRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.HighlightObjectsResult.FromString,
                _registered_method=True)
        self.HighlightPoint = channel.unary_unary(
                '/briosa.ViewControl/HighlightPoint',
                request_serializer=briosa_dot_view__control__pb2.HighlightPointRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.HighlightPointResult.FromString,
                _registered_method=True)
        self.HighlightRelationships = channel.unary_unary(
                '/briosa.ViewControl/HighlightRelationships',
                request_serializer=briosa_dot_view__control__pb2.HighlightRelationshipsRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.HighlightRelationshipsResult.FromString,
                _registered_method=True)
        self.LoadRibbonBarFromXmlFile = channel.unary_unary(
                '/briosa.ViewControl/LoadRibbonBarFromXmlFile',
                request_serializer=briosa_dot_view__control__pb2.LoadRibbonBarFromXmlFileRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.LoadRibbonBarFromXmlFileResult.FromString,
                _registered_method=True)
        self.RefreshViews = channel.unary_unary(
                '/briosa.ViewControl/RefreshViews',
                request_serializer=briosa_dot_view__control__pb2.RefreshViewsRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.RefreshViewsResult.FromString,
                _registered_method=True)
        self.ResetRibbonBarToDefault = channel.unary_unary(
                '/briosa.ViewControl/ResetRibbonBarToDefault',
                request_serializer=briosa_dot_view__control__pb2.ResetRibbonBarToDefaultRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ResetRibbonBarToDefaultResult.FromString,
                _registered_method=True)
        self.SavePointOfView = channel.unary_unary(
                '/briosa.ViewControl/SavePointOfView',
                request_serializer=briosa_dot_view__control__pb2.SavePointOfViewRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SavePointOfViewResult.FromString,
                _registered_method=True)
        self.SetBackgroundColor = channel.unary_unary(
                '/briosa.ViewControl/SetBackgroundColor',
                request_serializer=briosa_dot_view__control__pb2.SetBackgroundColorRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetBackgroundColorResult.FromString,
                _registered_method=True)
        self.SetMpWindowState = channel.unary_unary(
                '/briosa.ViewControl/SetMpWindowState',
                request_serializer=briosa_dot_view__control__pb2.SetMpWindowStateRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetMpWindowStateResult.FromString,
                _registered_method=True)
        self.SetObjectsColor = channel.unary_unary(
                '/briosa.ViewControl/SetObjectsColor',
                request_serializer=briosa_dot_view__control__pb2.SetObjectsColorRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetObjectsColorResult.FromString,
                _registered_method=True)
        self.SetObjectsTranslucency = channel.unary_unary(
                '/briosa.ViewControl/SetObjectsTranslucency',
                request_serializer=briosa_dot_view__control__pb2.SetObjectsTranslucencyRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetObjectsTranslucencyResult.FromString,
                _registered_method=True)
        self.SetPointOfView = channel.unary_unary(
                '/briosa.ViewControl/SetPointOfView',
                request_serializer=briosa_dot_view__control__pb2.SetPointOfViewRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetPointOfViewResult.FromString,
                _registered_method=True)
        self.SetPointOfViewFromFrame = channel.unary_unary(
                '/briosa.ViewControl/SetPointOfViewFromFrame',
                request_serializer=briosa_dot_view__control__pb2.SetPointOfViewFromFrameRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetPointOfViewFromFrameResult.FromString,
                _registered_method=True)
        self.SetPointOfViewFromInstrumentUpdates = channel.unary_unary(
                '/briosa.ViewControl/SetPointOfViewFromInstrumentUpdates',
                request_serializer=briosa_dot_view__control__pb2.SetPointOfViewFromInstrumentUpdatesRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetPointOfViewFromInstrumentUpdatesResult.FromString,
                _registered_method=True)
        self.SetRenderModeType = channel.unary_unary(
                '/briosa.ViewControl/SetRenderModeType',
                request_serializer=briosa_dot_view__control__pb2.SetRenderModeTypeRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetRenderModeTypeResult.FromString,
                _registered_method=True)
        self.SetSaWindowPos = channel.unary_unary(
                '/briosa.ViewControl/SetSaWindowPos',
                request_serializer=briosa_dot_view__control__pb2.SetSaWindowPosRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetSaWindowPosResult.FromString,
                _registered_method=True)
        self.SetSaWindowSize = channel.unary_unary(
                '/briosa.ViewControl/SetSaWindowSize',
                request_serializer=briosa_dot_view__control__pb2.SetSaWindowSizeRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetSaWindowSizeResult.FromString,
                _registered_method=True)
        self.SetSaWindowState = channel.unary_unary(
                '/briosa.ViewControl/SetSaWindowState',
                request_serializer=briosa_dot_view__control__pb2.SetSaWindowStateRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetSaWindowStateResult.FromString,
                _registered_method=True)
        self.SetTargetLabelsUseFullNames = channel.unary_unary(
                '/briosa.ViewControl/SetTargetLabelsUseFullNames',
                request_serializer=briosa_dot_view__control__pb2.SetTargetLabelsUseFullNamesRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetTargetLabelsUseFullNamesResult.FromString,
                _registered_method=True)
        self.SetToolkitVisibility = channel.unary_unary(
                '/briosa.ViewControl/SetToolkitVisibility',
                request_serializer=briosa_dot_view__control__pb2.SetToolkitVisibilityRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetToolkitVisibilityResult.FromString,
                _registered_method=True)
        self.SetViewClippingPlane = channel.unary_unary(
                '/briosa.ViewControl/SetViewClippingPlane',
                request_serializer=briosa_dot_view__control__pb2.SetViewClippingPlaneRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetViewClippingPlaneResult.FromString,
                _registered_method=True)
        self.SetWorkingColor = channel.unary_unary(
                '/briosa.ViewControl/SetWorkingColor',
                request_serializer=briosa_dot_view__control__pb2.SetWorkingColorRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetWorkingColorResult.FromString,
                _registered_method=True)
        self.SetWorkingColorAutoIncrement = channel.unary_unary(
                '/briosa.ViewControl/SetWorkingColorAutoIncrement',
                request_serializer=briosa_dot_view__control__pb2.SetWorkingColorAutoIncrementRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.SetWorkingColorAutoIncrementResult.FromString,
                _registered_method=True)
        self.ShowHideByObjectType = channel.unary_unary(
                '/briosa.ViewControl/ShowHideByObjectType',
                request_serializer=briosa_dot_view__control__pb2.ShowHideByObjectTypeRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHideByObjectTypeResult.FromString,
                _registered_method=True)
        self.ShowHideCalloutView = channel.unary_unary(
                '/briosa.ViewControl/ShowHideCalloutView',
                request_serializer=briosa_dot_view__control__pb2.ShowHideCalloutViewRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHideCalloutViewResult.FromString,
                _registered_method=True)
        self.ShowHideDimension = channel.unary_unary(
                '/briosa.ViewControl/ShowHideDimension',
                request_serializer=briosa_dot_view__control__pb2.ShowHideDimensionRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHideDimensionResult.FromString,
                _registered_method=True)
        self.ShowHidePoints = channel.unary_unary(
                '/briosa.ViewControl/ShowHidePoints',
                request_serializer=briosa_dot_view__control__pb2.ShowHidePointsRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHidePointsResult.FromString,
                _registered_method=True)
        self.ShowByObjectType = channel.unary_unary(
                '/briosa.ViewControl/ShowByObjectType',
                request_serializer=briosa_dot_view__control__pb2.ShowByObjectTypeRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowByObjectTypeResult.FromString,
                _registered_method=True)
        self.ShowItemsInTree = channel.unary_unary(
                '/briosa.ViewControl/ShowItemsInTree',
                request_serializer=briosa_dot_view__control__pb2.ShowItemsInTreeRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowItemsInTreeResult.FromString,
                _registered_method=True)
        self.ShowLabels = channel.unary_unary(
                '/briosa.ViewControl/ShowLabels',
                request_serializer=briosa_dot_view__control__pb2.ShowLabelsRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowLabelsResult.FromString,
                _registered_method=True)
        self.ShowObjects = channel.unary_unary(
                '/briosa.ViewControl/ShowObjects',
                request_serializer=briosa_dot_view__control__pb2.ShowObjectsRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowObjectsResult.FromString,
                _registered_method=True)
        self.ShowHideAnnotationsForDatums = channel.unary_unary(
                '/briosa.ViewControl/ShowHideAnnotationsForDatums',
                request_serializer=briosa_dot_view__control__pb2.ShowHideAnnotationsForDatumsRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHideAnnotationsForDatumsResult.FromString,
                _registered_method=True)
        self.ShowHideAnnotationsForFeatureChecks = channel.unary_unary(
                '/briosa.ViewControl/ShowHideAnnotationsForFeatureChecks',
                request_serializer=briosa_dot_view__control__pb2.ShowHideAnnotationsForFeatureChecksRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHideAnnotationsForFeatureChecksResult.FromString,
                _registered_method=True)
        self.ShowHideInspectionBar = channel.unary_unary(
                '/briosa.ViewControl/ShowHideInspectionBar',
                request_serializer=briosa_dot_view__control__pb2.ShowHideInspectionBarRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHideInspectionBarResult.FromString,
                _registered_method=True)
        self.ShowHideInstrumentInterface = channel.unary_unary(
                '/briosa.ViewControl/ShowHideInstrumentInterface',
                request_serializer=briosa_dot_view__control__pb2.ShowHideInstrumentInterfaceRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHideInstrumentInterfaceResult.FromString,
                _registered_method=True)
        self.ShowHideInstrumentProbeTip = channel.unary_unary(
                '/briosa.ViewControl/ShowHideInstrumentProbeTip',
                request_serializer=briosa_dot_view__control__pb2.ShowHideInstrumentProbeTipRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHideInstrumentProbeTipResult.FromString,
                _registered_method=True)
        self.ShowHideInstruments = channel.unary_unary(
                '/briosa.ViewControl/ShowHideInstruments',
                request_serializer=briosa_dot_view__control__pb2.ShowHideInstrumentsRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHideInstrumentsResult.FromString,
                _registered_method=True)
        self.ShowHideRelationshipReport = channel.unary_unary(
                '/briosa.ViewControl/ShowHideRelationshipReport',
                request_serializer=briosa_dot_view__control__pb2.ShowHideRelationshipReportRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHideRelationshipReportResult.FromString,
                _registered_method=True)
        self.ShowHideRelationshipWatch = channel.unary_unary(
                '/briosa.ViewControl/ShowHideRelationshipWatch',
                request_serializer=briosa_dot_view__control__pb2.ShowHideRelationshipWatchRequest.SerializeToString,
                response_deserializer=briosa_dot_view__control__pb2.ShowHideRelationshipWatchResult.FromString,
                _registered_method=True)


class ViewControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AutoScale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CenterGraphicsAboutObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CenterGraphicsAboutPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DefinePointOfView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveClippingPlanes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPointOfViewParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HideAllCalloutViews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HideObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HighlightObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HighlightPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HighlightRelationships(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadRibbonBarFromXmlFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshViews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetRibbonBarToDefault(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SavePointOfView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBackgroundColor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMpWindowState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetObjectsColor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetObjectsTranslucency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPointOfView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPointOfViewFromFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPointOfViewFromInstrumentUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRenderModeType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSaWindowPos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSaWindowSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSaWindowState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTargetLabelsUseFullNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetToolkitVisibility(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetViewClippingPlane(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWorkingColor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWorkingColorAutoIncrement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHideByObjectType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHideCalloutView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHideDimension(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHidePoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowByObjectType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowItemsInTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowLabels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHideAnnotationsForDatums(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHideAnnotationsForFeatureChecks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHideInspectionBar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHideInstrumentInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHideInstrumentProbeTip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHideInstruments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHideRelationshipReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowHideRelationshipWatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViewControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AutoScale': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoScale,
                    request_deserializer=briosa_dot_view__control__pb2.AutoScaleRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.AutoScaleResult.SerializeToString,
            ),
            'CenterGraphicsAboutObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.CenterGraphicsAboutObjects,
                    request_deserializer=briosa_dot_view__control__pb2.CenterGraphicsAboutObjectsRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.CenterGraphicsAboutObjectsResult.SerializeToString,
            ),
            'CenterGraphicsAboutPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.CenterGraphicsAboutPoint,
                    request_deserializer=briosa_dot_view__control__pb2.CenterGraphicsAboutPointRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.CenterGraphicsAboutPointResult.SerializeToString,
            ),
            'DefinePointOfView': grpc.unary_unary_rpc_method_handler(
                    servicer.DefinePointOfView,
                    request_deserializer=briosa_dot_view__control__pb2.DefinePointOfViewRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.DefinePointOfViewResult.SerializeToString,
            ),
            'GetActiveClippingPlanes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveClippingPlanes,
                    request_deserializer=briosa_dot_view__control__pb2.GetActiveClippingPlanesRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.GetActiveClippingPlanesResult.SerializeToString,
            ),
            'GetPointOfViewParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPointOfViewParameters,
                    request_deserializer=briosa_dot_view__control__pb2.GetPointOfViewParametersRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.GetPointOfViewParametersResult.SerializeToString,
            ),
            'HideAllCalloutViews': grpc.unary_unary_rpc_method_handler(
                    servicer.HideAllCalloutViews,
                    request_deserializer=briosa_dot_view__control__pb2.HideAllCalloutViewsRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.HideAllCalloutViewsResult.SerializeToString,
            ),
            'HideObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.HideObjects,
                    request_deserializer=briosa_dot_view__control__pb2.HideObjectsRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.HideObjectsResult.SerializeToString,
            ),
            'HighlightObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.HighlightObjects,
                    request_deserializer=briosa_dot_view__control__pb2.HighlightObjectsRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.HighlightObjectsResult.SerializeToString,
            ),
            'HighlightPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.HighlightPoint,
                    request_deserializer=briosa_dot_view__control__pb2.HighlightPointRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.HighlightPointResult.SerializeToString,
            ),
            'HighlightRelationships': grpc.unary_unary_rpc_method_handler(
                    servicer.HighlightRelationships,
                    request_deserializer=briosa_dot_view__control__pb2.HighlightRelationshipsRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.HighlightRelationshipsResult.SerializeToString,
            ),
            'LoadRibbonBarFromXmlFile': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadRibbonBarFromXmlFile,
                    request_deserializer=briosa_dot_view__control__pb2.LoadRibbonBarFromXmlFileRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.LoadRibbonBarFromXmlFileResult.SerializeToString,
            ),
            'RefreshViews': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshViews,
                    request_deserializer=briosa_dot_view__control__pb2.RefreshViewsRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.RefreshViewsResult.SerializeToString,
            ),
            'ResetRibbonBarToDefault': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetRibbonBarToDefault,
                    request_deserializer=briosa_dot_view__control__pb2.ResetRibbonBarToDefaultRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ResetRibbonBarToDefaultResult.SerializeToString,
            ),
            'SavePointOfView': grpc.unary_unary_rpc_method_handler(
                    servicer.SavePointOfView,
                    request_deserializer=briosa_dot_view__control__pb2.SavePointOfViewRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SavePointOfViewResult.SerializeToString,
            ),
            'SetBackgroundColor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBackgroundColor,
                    request_deserializer=briosa_dot_view__control__pb2.SetBackgroundColorRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetBackgroundColorResult.SerializeToString,
            ),
            'SetMpWindowState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMpWindowState,
                    request_deserializer=briosa_dot_view__control__pb2.SetMpWindowStateRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetMpWindowStateResult.SerializeToString,
            ),
            'SetObjectsColor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetObjectsColor,
                    request_deserializer=briosa_dot_view__control__pb2.SetObjectsColorRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetObjectsColorResult.SerializeToString,
            ),
            'SetObjectsTranslucency': grpc.unary_unary_rpc_method_handler(
                    servicer.SetObjectsTranslucency,
                    request_deserializer=briosa_dot_view__control__pb2.SetObjectsTranslucencyRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetObjectsTranslucencyResult.SerializeToString,
            ),
            'SetPointOfView': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPointOfView,
                    request_deserializer=briosa_dot_view__control__pb2.SetPointOfViewRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetPointOfViewResult.SerializeToString,
            ),
            'SetPointOfViewFromFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPointOfViewFromFrame,
                    request_deserializer=briosa_dot_view__control__pb2.SetPointOfViewFromFrameRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetPointOfViewFromFrameResult.SerializeToString,
            ),
            'SetPointOfViewFromInstrumentUpdates': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPointOfViewFromInstrumentUpdates,
                    request_deserializer=briosa_dot_view__control__pb2.SetPointOfViewFromInstrumentUpdatesRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetPointOfViewFromInstrumentUpdatesResult.SerializeToString,
            ),
            'SetRenderModeType': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRenderModeType,
                    request_deserializer=briosa_dot_view__control__pb2.SetRenderModeTypeRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetRenderModeTypeResult.SerializeToString,
            ),
            'SetSaWindowPos': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSaWindowPos,
                    request_deserializer=briosa_dot_view__control__pb2.SetSaWindowPosRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetSaWindowPosResult.SerializeToString,
            ),
            'SetSaWindowSize': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSaWindowSize,
                    request_deserializer=briosa_dot_view__control__pb2.SetSaWindowSizeRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetSaWindowSizeResult.SerializeToString,
            ),
            'SetSaWindowState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSaWindowState,
                    request_deserializer=briosa_dot_view__control__pb2.SetSaWindowStateRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetSaWindowStateResult.SerializeToString,
            ),
            'SetTargetLabelsUseFullNames': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTargetLabelsUseFullNames,
                    request_deserializer=briosa_dot_view__control__pb2.SetTargetLabelsUseFullNamesRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetTargetLabelsUseFullNamesResult.SerializeToString,
            ),
            'SetToolkitVisibility': grpc.unary_unary_rpc_method_handler(
                    servicer.SetToolkitVisibility,
                    request_deserializer=briosa_dot_view__control__pb2.SetToolkitVisibilityRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetToolkitVisibilityResult.SerializeToString,
            ),
            'SetViewClippingPlane': grpc.unary_unary_rpc_method_handler(
                    servicer.SetViewClippingPlane,
                    request_deserializer=briosa_dot_view__control__pb2.SetViewClippingPlaneRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetViewClippingPlaneResult.SerializeToString,
            ),
            'SetWorkingColor': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWorkingColor,
                    request_deserializer=briosa_dot_view__control__pb2.SetWorkingColorRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetWorkingColorResult.SerializeToString,
            ),
            'SetWorkingColorAutoIncrement': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWorkingColorAutoIncrement,
                    request_deserializer=briosa_dot_view__control__pb2.SetWorkingColorAutoIncrementRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.SetWorkingColorAutoIncrementResult.SerializeToString,
            ),
            'ShowHideByObjectType': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHideByObjectType,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHideByObjectTypeRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHideByObjectTypeResult.SerializeToString,
            ),
            'ShowHideCalloutView': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHideCalloutView,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHideCalloutViewRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHideCalloutViewResult.SerializeToString,
            ),
            'ShowHideDimension': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHideDimension,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHideDimensionRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHideDimensionResult.SerializeToString,
            ),
            'ShowHidePoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHidePoints,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHidePointsRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHidePointsResult.SerializeToString,
            ),
            'ShowByObjectType': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowByObjectType,
                    request_deserializer=briosa_dot_view__control__pb2.ShowByObjectTypeRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowByObjectTypeResult.SerializeToString,
            ),
            'ShowItemsInTree': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowItemsInTree,
                    request_deserializer=briosa_dot_view__control__pb2.ShowItemsInTreeRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowItemsInTreeResult.SerializeToString,
            ),
            'ShowLabels': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowLabels,
                    request_deserializer=briosa_dot_view__control__pb2.ShowLabelsRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowLabelsResult.SerializeToString,
            ),
            'ShowObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowObjects,
                    request_deserializer=briosa_dot_view__control__pb2.ShowObjectsRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowObjectsResult.SerializeToString,
            ),
            'ShowHideAnnotationsForDatums': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHideAnnotationsForDatums,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHideAnnotationsForDatumsRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHideAnnotationsForDatumsResult.SerializeToString,
            ),
            'ShowHideAnnotationsForFeatureChecks': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHideAnnotationsForFeatureChecks,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHideAnnotationsForFeatureChecksRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHideAnnotationsForFeatureChecksResult.SerializeToString,
            ),
            'ShowHideInspectionBar': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHideInspectionBar,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHideInspectionBarRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHideInspectionBarResult.SerializeToString,
            ),
            'ShowHideInstrumentInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHideInstrumentInterface,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHideInstrumentInterfaceRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHideInstrumentInterfaceResult.SerializeToString,
            ),
            'ShowHideInstrumentProbeTip': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHideInstrumentProbeTip,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHideInstrumentProbeTipRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHideInstrumentProbeTipResult.SerializeToString,
            ),
            'ShowHideInstruments': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHideInstruments,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHideInstrumentsRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHideInstrumentsResult.SerializeToString,
            ),
            'ShowHideRelationshipReport': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHideRelationshipReport,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHideRelationshipReportRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHideRelationshipReportResult.SerializeToString,
            ),
            'ShowHideRelationshipWatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowHideRelationshipWatch,
                    request_deserializer=briosa_dot_view__control__pb2.ShowHideRelationshipWatchRequest.FromString,
                    response_serializer=briosa_dot_view__control__pb2.ShowHideRelationshipWatchResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'briosa.ViewControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('briosa.ViewControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ViewControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AutoScale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/AutoScale',
            briosa_dot_view__control__pb2.AutoScaleRequest.SerializeToString,
            briosa_dot_view__control__pb2.AutoScaleResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CenterGraphicsAboutObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/CenterGraphicsAboutObjects',
            briosa_dot_view__control__pb2.CenterGraphicsAboutObjectsRequest.SerializeToString,
            briosa_dot_view__control__pb2.CenterGraphicsAboutObjectsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CenterGraphicsAboutPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/CenterGraphicsAboutPoint',
            briosa_dot_view__control__pb2.CenterGraphicsAboutPointRequest.SerializeToString,
            briosa_dot_view__control__pb2.CenterGraphicsAboutPointResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DefinePointOfView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/DefinePointOfView',
            briosa_dot_view__control__pb2.DefinePointOfViewRequest.SerializeToString,
            briosa_dot_view__control__pb2.DefinePointOfViewResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveClippingPlanes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/GetActiveClippingPlanes',
            briosa_dot_view__control__pb2.GetActiveClippingPlanesRequest.SerializeToString,
            briosa_dot_view__control__pb2.GetActiveClippingPlanesResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPointOfViewParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/GetPointOfViewParameters',
            briosa_dot_view__control__pb2.GetPointOfViewParametersRequest.SerializeToString,
            briosa_dot_view__control__pb2.GetPointOfViewParametersResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HideAllCalloutViews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/HideAllCalloutViews',
            briosa_dot_view__control__pb2.HideAllCalloutViewsRequest.SerializeToString,
            briosa_dot_view__control__pb2.HideAllCalloutViewsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HideObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/HideObjects',
            briosa_dot_view__control__pb2.HideObjectsRequest.SerializeToString,
            briosa_dot_view__control__pb2.HideObjectsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HighlightObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/HighlightObjects',
            briosa_dot_view__control__pb2.HighlightObjectsRequest.SerializeToString,
            briosa_dot_view__control__pb2.HighlightObjectsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HighlightPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/HighlightPoint',
            briosa_dot_view__control__pb2.HighlightPointRequest.SerializeToString,
            briosa_dot_view__control__pb2.HighlightPointResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HighlightRelationships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/HighlightRelationships',
            briosa_dot_view__control__pb2.HighlightRelationshipsRequest.SerializeToString,
            briosa_dot_view__control__pb2.HighlightRelationshipsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadRibbonBarFromXmlFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/LoadRibbonBarFromXmlFile',
            briosa_dot_view__control__pb2.LoadRibbonBarFromXmlFileRequest.SerializeToString,
            briosa_dot_view__control__pb2.LoadRibbonBarFromXmlFileResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshViews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/RefreshViews',
            briosa_dot_view__control__pb2.RefreshViewsRequest.SerializeToString,
            briosa_dot_view__control__pb2.RefreshViewsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetRibbonBarToDefault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ResetRibbonBarToDefault',
            briosa_dot_view__control__pb2.ResetRibbonBarToDefaultRequest.SerializeToString,
            briosa_dot_view__control__pb2.ResetRibbonBarToDefaultResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SavePointOfView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SavePointOfView',
            briosa_dot_view__control__pb2.SavePointOfViewRequest.SerializeToString,
            briosa_dot_view__control__pb2.SavePointOfViewResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBackgroundColor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetBackgroundColor',
            briosa_dot_view__control__pb2.SetBackgroundColorRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetBackgroundColorResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMpWindowState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetMpWindowState',
            briosa_dot_view__control__pb2.SetMpWindowStateRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetMpWindowStateResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetObjectsColor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetObjectsColor',
            briosa_dot_view__control__pb2.SetObjectsColorRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetObjectsColorResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetObjectsTranslucency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetObjectsTranslucency',
            briosa_dot_view__control__pb2.SetObjectsTranslucencyRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetObjectsTranslucencyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPointOfView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetPointOfView',
            briosa_dot_view__control__pb2.SetPointOfViewRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetPointOfViewResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPointOfViewFromFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetPointOfViewFromFrame',
            briosa_dot_view__control__pb2.SetPointOfViewFromFrameRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetPointOfViewFromFrameResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPointOfViewFromInstrumentUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetPointOfViewFromInstrumentUpdates',
            briosa_dot_view__control__pb2.SetPointOfViewFromInstrumentUpdatesRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetPointOfViewFromInstrumentUpdatesResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRenderModeType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetRenderModeType',
            briosa_dot_view__control__pb2.SetRenderModeTypeRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetRenderModeTypeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSaWindowPos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetSaWindowPos',
            briosa_dot_view__control__pb2.SetSaWindowPosRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetSaWindowPosResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSaWindowSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetSaWindowSize',
            briosa_dot_view__control__pb2.SetSaWindowSizeRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetSaWindowSizeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSaWindowState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetSaWindowState',
            briosa_dot_view__control__pb2.SetSaWindowStateRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetSaWindowStateResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTargetLabelsUseFullNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetTargetLabelsUseFullNames',
            briosa_dot_view__control__pb2.SetTargetLabelsUseFullNamesRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetTargetLabelsUseFullNamesResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetToolkitVisibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetToolkitVisibility',
            briosa_dot_view__control__pb2.SetToolkitVisibilityRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetToolkitVisibilityResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetViewClippingPlane(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetViewClippingPlane',
            briosa_dot_view__control__pb2.SetViewClippingPlaneRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetViewClippingPlaneResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWorkingColor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetWorkingColor',
            briosa_dot_view__control__pb2.SetWorkingColorRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetWorkingColorResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWorkingColorAutoIncrement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/SetWorkingColorAutoIncrement',
            briosa_dot_view__control__pb2.SetWorkingColorAutoIncrementRequest.SerializeToString,
            briosa_dot_view__control__pb2.SetWorkingColorAutoIncrementResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHideByObjectType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHideByObjectType',
            briosa_dot_view__control__pb2.ShowHideByObjectTypeRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHideByObjectTypeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHideCalloutView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHideCalloutView',
            briosa_dot_view__control__pb2.ShowHideCalloutViewRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHideCalloutViewResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHideDimension(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHideDimension',
            briosa_dot_view__control__pb2.ShowHideDimensionRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHideDimensionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHidePoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHidePoints',
            briosa_dot_view__control__pb2.ShowHidePointsRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHidePointsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowByObjectType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowByObjectType',
            briosa_dot_view__control__pb2.ShowByObjectTypeRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowByObjectTypeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowItemsInTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowItemsInTree',
            briosa_dot_view__control__pb2.ShowItemsInTreeRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowItemsInTreeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowLabels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowLabels',
            briosa_dot_view__control__pb2.ShowLabelsRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowLabelsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowObjects',
            briosa_dot_view__control__pb2.ShowObjectsRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowObjectsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHideAnnotationsForDatums(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHideAnnotationsForDatums',
            briosa_dot_view__control__pb2.ShowHideAnnotationsForDatumsRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHideAnnotationsForDatumsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHideAnnotationsForFeatureChecks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHideAnnotationsForFeatureChecks',
            briosa_dot_view__control__pb2.ShowHideAnnotationsForFeatureChecksRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHideAnnotationsForFeatureChecksResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHideInspectionBar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHideInspectionBar',
            briosa_dot_view__control__pb2.ShowHideInspectionBarRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHideInspectionBarResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHideInstrumentInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHideInstrumentInterface',
            briosa_dot_view__control__pb2.ShowHideInstrumentInterfaceRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHideInstrumentInterfaceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHideInstrumentProbeTip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHideInstrumentProbeTip',
            briosa_dot_view__control__pb2.ShowHideInstrumentProbeTipRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHideInstrumentProbeTipResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHideInstruments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHideInstruments',
            briosa_dot_view__control__pb2.ShowHideInstrumentsRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHideInstrumentsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHideRelationshipReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHideRelationshipReport',
            briosa_dot_view__control__pb2.ShowHideRelationshipReportRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHideRelationshipReportResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowHideRelationshipWatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.ViewControl/ShowHideRelationshipWatch',
            briosa_dot_view__control__pb2.ShowHideRelationshipWatchRequest.SerializeToString,
            briosa_dot_view__control__pb2.ShowHideRelationshipWatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
