# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from briosa import variables_pb2 as briosa_dot_variables__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in briosa/variables_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VariablesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddDoubleToNamedDoubleListVariable = channel.unary_unary(
                '/briosa.Variables/AddDoubleToNamedDoubleListVariable',
                request_serializer=briosa_dot_variables__pb2.AddDoubleToNamedDoubleListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.AddDoubleToNamedDoubleListVariableResult.FromString,
                _registered_method=True)
        self.ClearNamedDoubleListVariable = channel.unary_unary(
                '/briosa.Variables/ClearNamedDoubleListVariable',
                request_serializer=briosa_dot_variables__pb2.ClearNamedDoubleListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.ClearNamedDoubleListVariableResult.FromString,
                _registered_method=True)
        self.DeleteVariable = channel.unary_unary(
                '/briosa.Variables/DeleteVariable',
                request_serializer=briosa_dot_variables__pb2.DeleteVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.DeleteVariableResult.FromString,
                _registered_method=True)
        self.DeleteVariablesWildcardMatch = channel.unary_unary(
                '/briosa.Variables/DeleteVariablesWildcardMatch',
                request_serializer=briosa_dot_variables__pb2.DeleteVariablesWildcardMatchRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.DeleteVariablesWildcardMatchResult.FromString,
                _registered_method=True)
        self.GetBooleanVariable = channel.unary_unary(
                '/briosa.Variables/GetBooleanVariable',
                request_serializer=briosa_dot_variables__pb2.GetBooleanVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetBooleanVariableResult.FromString,
                _registered_method=True)
        self.GetCollectionObjectNameVariable = channel.unary_unary(
                '/briosa.Variables/GetCollectionObjectNameVariable',
                request_serializer=briosa_dot_variables__pb2.GetCollectionObjectNameVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetCollectionObjectNameVariableResult.FromString,
                _registered_method=True)
        self.GetCollectionObjectRefListVariable = channel.unary_unary(
                '/briosa.Variables/GetCollectionObjectRefListVariable',
                request_serializer=briosa_dot_variables__pb2.GetCollectionObjectRefListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetCollectionObjectRefListVariableResult.FromString,
                _registered_method=True)
        self.GetDoubleVariable = channel.unary_unary(
                '/briosa.Variables/GetDoubleVariable',
                request_serializer=briosa_dot_variables__pb2.GetDoubleVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetDoubleVariableResult.FromString,
                _registered_method=True)
        self.GetIntegerVariable = channel.unary_unary(
                '/briosa.Variables/GetIntegerVariable',
                request_serializer=briosa_dot_variables__pb2.GetIntegerVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetIntegerVariableResult.FromString,
                _registered_method=True)
        self.GetNamedDoubleListVariable = channel.unary_unary(
                '/briosa.Variables/GetNamedDoubleListVariable',
                request_serializer=briosa_dot_variables__pb2.GetNamedDoubleListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetNamedDoubleListVariableResult.FromString,
                _registered_method=True)
        self.GetNamedDoubleListVariableMinMax = channel.unary_unary(
                '/briosa.Variables/GetNamedDoubleListVariableMinMax',
                request_serializer=briosa_dot_variables__pb2.GetNamedDoubleListVariableMinMaxRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetNamedDoubleListVariableMinMaxResult.FromString,
                _registered_method=True)
        self.GetPointNameRefListVariable = channel.unary_unary(
                '/briosa.Variables/GetPointNameRefListVariable',
                request_serializer=briosa_dot_variables__pb2.GetPointNameRefListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetPointNameRefListVariableResult.FromString,
                _registered_method=True)
        self.GetPointNameVariable = channel.unary_unary(
                '/briosa.Variables/GetPointNameVariable',
                request_serializer=briosa_dot_variables__pb2.GetPointNameVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetPointNameVariableResult.FromString,
                _registered_method=True)
        self.GetRelationshipRefListVariable = channel.unary_unary(
                '/briosa.Variables/GetRelationshipRefListVariable',
                request_serializer=briosa_dot_variables__pb2.GetRelationshipRefListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetRelationshipRefListVariableResult.FromString,
                _registered_method=True)
        self.GetReportItemsReferenceListVariable = channel.unary_unary(
                '/briosa.Variables/GetReportItemsReferenceListVariable',
                request_serializer=briosa_dot_variables__pb2.GetReportItemsReferenceListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetReportItemsReferenceListVariableResult.FromString,
                _registered_method=True)
        self.GetStringRefListVariable = channel.unary_unary(
                '/briosa.Variables/GetStringRefListVariable',
                request_serializer=briosa_dot_variables__pb2.GetStringRefListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetStringRefListVariableResult.FromString,
                _registered_method=True)
        self.GetStringVariable = channel.unary_unary(
                '/briosa.Variables/GetStringVariable',
                request_serializer=briosa_dot_variables__pb2.GetStringVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetStringVariableResult.FromString,
                _registered_method=True)
        self.GetTransformVariable = channel.unary_unary(
                '/briosa.Variables/GetTransformVariable',
                request_serializer=briosa_dot_variables__pb2.GetTransformVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetTransformVariableResult.FromString,
                _registered_method=True)
        self.GetVectorNameRefListVariable = channel.unary_unary(
                '/briosa.Variables/GetVectorNameRefListVariable',
                request_serializer=briosa_dot_variables__pb2.GetVectorNameRefListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetVectorNameRefListVariableResult.FromString,
                _registered_method=True)
        self.GetVectorVariable = channel.unary_unary(
                '/briosa.Variables/GetVectorVariable',
                request_serializer=briosa_dot_variables__pb2.GetVectorVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.GetVectorVariableResult.FromString,
                _registered_method=True)
        self.SetBooleanVariable = channel.unary_unary(
                '/briosa.Variables/SetBooleanVariable',
                request_serializer=briosa_dot_variables__pb2.SetBooleanVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetBooleanVariableResult.FromString,
                _registered_method=True)
        self.SetCollectionObjectNameVariable = channel.unary_unary(
                '/briosa.Variables/SetCollectionObjectNameVariable',
                request_serializer=briosa_dot_variables__pb2.SetCollectionObjectNameVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetCollectionObjectNameVariableResult.FromString,
                _registered_method=True)
        self.SetCollectionObjectRefListVariable = channel.unary_unary(
                '/briosa.Variables/SetCollectionObjectRefListVariable',
                request_serializer=briosa_dot_variables__pb2.SetCollectionObjectRefListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetCollectionObjectRefListVariableResult.FromString,
                _registered_method=True)
        self.SetDoubleVariable = channel.unary_unary(
                '/briosa.Variables/SetDoubleVariable',
                request_serializer=briosa_dot_variables__pb2.SetDoubleVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetDoubleVariableResult.FromString,
                _registered_method=True)
        self.SetFontVariable = channel.unary_unary(
                '/briosa.Variables/SetFontVariable',
                request_serializer=briosa_dot_variables__pb2.SetFontVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetFontVariableResult.FromString,
                _registered_method=True)
        self.SetIntegerVariable = channel.unary_unary(
                '/briosa.Variables/SetIntegerVariable',
                request_serializer=briosa_dot_variables__pb2.SetIntegerVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetIntegerVariableResult.FromString,
                _registered_method=True)
        self.SetNamedDoubleListVariable = channel.unary_unary(
                '/briosa.Variables/SetNamedDoubleListVariable',
                request_serializer=briosa_dot_variables__pb2.SetNamedDoubleListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetNamedDoubleListVariableResult.FromString,
                _registered_method=True)
        self.SetPointNameRefListVariable = channel.unary_unary(
                '/briosa.Variables/SetPointNameRefListVariable',
                request_serializer=briosa_dot_variables__pb2.SetPointNameRefListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetPointNameRefListVariableResult.FromString,
                _registered_method=True)
        self.SetPointNameVariable = channel.unary_unary(
                '/briosa.Variables/SetPointNameVariable',
                request_serializer=briosa_dot_variables__pb2.SetPointNameVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetPointNameVariableResult.FromString,
                _registered_method=True)
        self.SetRelationshipRefListVariable = channel.unary_unary(
                '/briosa.Variables/SetRelationshipRefListVariable',
                request_serializer=briosa_dot_variables__pb2.SetRelationshipRefListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetRelationshipRefListVariableResult.FromString,
                _registered_method=True)
        self.SetReportItemsReferenceListVariable = channel.unary_unary(
                '/briosa.Variables/SetReportItemsReferenceListVariable',
                request_serializer=briosa_dot_variables__pb2.SetReportItemsReferenceListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetReportItemsReferenceListVariableResult.FromString,
                _registered_method=True)
        self.SetStringRefListVariable = channel.unary_unary(
                '/briosa.Variables/SetStringRefListVariable',
                request_serializer=briosa_dot_variables__pb2.SetStringRefListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetStringRefListVariableResult.FromString,
                _registered_method=True)
        self.SetStringVariable = channel.unary_unary(
                '/briosa.Variables/SetStringVariable',
                request_serializer=briosa_dot_variables__pb2.SetStringVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetStringVariableResult.FromString,
                _registered_method=True)
        self.SetTransformVariable = channel.unary_unary(
                '/briosa.Variables/SetTransformVariable',
                request_serializer=briosa_dot_variables__pb2.SetTransformVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetTransformVariableResult.FromString,
                _registered_method=True)
        self.SetVectorNameRefListVariable = channel.unary_unary(
                '/briosa.Variables/SetVectorNameRefListVariable',
                request_serializer=briosa_dot_variables__pb2.SetVectorNameRefListVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetVectorNameRefListVariableResult.FromString,
                _registered_method=True)
        self.SetVectorVariable = channel.unary_unary(
                '/briosa.Variables/SetVectorVariable',
                request_serializer=briosa_dot_variables__pb2.SetVectorVariableRequest.SerializeToString,
                response_deserializer=briosa_dot_variables__pb2.SetVectorVariableResult.FromString,
                _registered_method=True)


class VariablesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddDoubleToNamedDoubleListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearNamedDoubleListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVariablesWildcardMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooleanVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionObjectNameVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionObjectRefListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDoubleVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntegerVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNamedDoubleListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNamedDoubleListVariableMinMax(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPointNameRefListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPointNameVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelationshipRefListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReportItemsReferenceListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStringRefListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStringVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransformVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVectorNameRefListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVectorVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBooleanVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCollectionObjectNameVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCollectionObjectRefListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDoubleVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFontVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIntegerVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNamedDoubleListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPointNameRefListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPointNameVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRelationshipRefListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReportItemsReferenceListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStringRefListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStringVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTransformVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVectorNameRefListVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVectorVariable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VariablesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddDoubleToNamedDoubleListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDoubleToNamedDoubleListVariable,
                    request_deserializer=briosa_dot_variables__pb2.AddDoubleToNamedDoubleListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.AddDoubleToNamedDoubleListVariableResult.SerializeToString,
            ),
            'ClearNamedDoubleListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearNamedDoubleListVariable,
                    request_deserializer=briosa_dot_variables__pb2.ClearNamedDoubleListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.ClearNamedDoubleListVariableResult.SerializeToString,
            ),
            'DeleteVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVariable,
                    request_deserializer=briosa_dot_variables__pb2.DeleteVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.DeleteVariableResult.SerializeToString,
            ),
            'DeleteVariablesWildcardMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVariablesWildcardMatch,
                    request_deserializer=briosa_dot_variables__pb2.DeleteVariablesWildcardMatchRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.DeleteVariablesWildcardMatchResult.SerializeToString,
            ),
            'GetBooleanVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooleanVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetBooleanVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetBooleanVariableResult.SerializeToString,
            ),
            'GetCollectionObjectNameVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionObjectNameVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetCollectionObjectNameVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetCollectionObjectNameVariableResult.SerializeToString,
            ),
            'GetCollectionObjectRefListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionObjectRefListVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetCollectionObjectRefListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetCollectionObjectRefListVariableResult.SerializeToString,
            ),
            'GetDoubleVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDoubleVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetDoubleVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetDoubleVariableResult.SerializeToString,
            ),
            'GetIntegerVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntegerVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetIntegerVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetIntegerVariableResult.SerializeToString,
            ),
            'GetNamedDoubleListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNamedDoubleListVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetNamedDoubleListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetNamedDoubleListVariableResult.SerializeToString,
            ),
            'GetNamedDoubleListVariableMinMax': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNamedDoubleListVariableMinMax,
                    request_deserializer=briosa_dot_variables__pb2.GetNamedDoubleListVariableMinMaxRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetNamedDoubleListVariableMinMaxResult.SerializeToString,
            ),
            'GetPointNameRefListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPointNameRefListVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetPointNameRefListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetPointNameRefListVariableResult.SerializeToString,
            ),
            'GetPointNameVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPointNameVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetPointNameVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetPointNameVariableResult.SerializeToString,
            ),
            'GetRelationshipRefListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelationshipRefListVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetRelationshipRefListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetRelationshipRefListVariableResult.SerializeToString,
            ),
            'GetReportItemsReferenceListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReportItemsReferenceListVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetReportItemsReferenceListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetReportItemsReferenceListVariableResult.SerializeToString,
            ),
            'GetStringRefListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStringRefListVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetStringRefListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetStringRefListVariableResult.SerializeToString,
            ),
            'GetStringVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStringVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetStringVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetStringVariableResult.SerializeToString,
            ),
            'GetTransformVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransformVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetTransformVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetTransformVariableResult.SerializeToString,
            ),
            'GetVectorNameRefListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVectorNameRefListVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetVectorNameRefListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetVectorNameRefListVariableResult.SerializeToString,
            ),
            'GetVectorVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVectorVariable,
                    request_deserializer=briosa_dot_variables__pb2.GetVectorVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.GetVectorVariableResult.SerializeToString,
            ),
            'SetBooleanVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBooleanVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetBooleanVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetBooleanVariableResult.SerializeToString,
            ),
            'SetCollectionObjectNameVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCollectionObjectNameVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetCollectionObjectNameVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetCollectionObjectNameVariableResult.SerializeToString,
            ),
            'SetCollectionObjectRefListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCollectionObjectRefListVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetCollectionObjectRefListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetCollectionObjectRefListVariableResult.SerializeToString,
            ),
            'SetDoubleVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDoubleVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetDoubleVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetDoubleVariableResult.SerializeToString,
            ),
            'SetFontVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFontVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetFontVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetFontVariableResult.SerializeToString,
            ),
            'SetIntegerVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIntegerVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetIntegerVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetIntegerVariableResult.SerializeToString,
            ),
            'SetNamedDoubleListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNamedDoubleListVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetNamedDoubleListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetNamedDoubleListVariableResult.SerializeToString,
            ),
            'SetPointNameRefListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPointNameRefListVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetPointNameRefListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetPointNameRefListVariableResult.SerializeToString,
            ),
            'SetPointNameVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPointNameVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetPointNameVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetPointNameVariableResult.SerializeToString,
            ),
            'SetRelationshipRefListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRelationshipRefListVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetRelationshipRefListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetRelationshipRefListVariableResult.SerializeToString,
            ),
            'SetReportItemsReferenceListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReportItemsReferenceListVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetReportItemsReferenceListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetReportItemsReferenceListVariableResult.SerializeToString,
            ),
            'SetStringRefListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStringRefListVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetStringRefListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetStringRefListVariableResult.SerializeToString,
            ),
            'SetStringVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStringVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetStringVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetStringVariableResult.SerializeToString,
            ),
            'SetTransformVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTransformVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetTransformVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetTransformVariableResult.SerializeToString,
            ),
            'SetVectorNameRefListVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVectorNameRefListVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetVectorNameRefListVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetVectorNameRefListVariableResult.SerializeToString,
            ),
            'SetVectorVariable': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVectorVariable,
                    request_deserializer=briosa_dot_variables__pb2.SetVectorVariableRequest.FromString,
                    response_serializer=briosa_dot_variables__pb2.SetVectorVariableResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'briosa.Variables', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('briosa.Variables', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Variables(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddDoubleToNamedDoubleListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/AddDoubleToNamedDoubleListVariable',
            briosa_dot_variables__pb2.AddDoubleToNamedDoubleListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.AddDoubleToNamedDoubleListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearNamedDoubleListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/ClearNamedDoubleListVariable',
            briosa_dot_variables__pb2.ClearNamedDoubleListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.ClearNamedDoubleListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/DeleteVariable',
            briosa_dot_variables__pb2.DeleteVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.DeleteVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVariablesWildcardMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/DeleteVariablesWildcardMatch',
            briosa_dot_variables__pb2.DeleteVariablesWildcardMatchRequest.SerializeToString,
            briosa_dot_variables__pb2.DeleteVariablesWildcardMatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBooleanVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetBooleanVariable',
            briosa_dot_variables__pb2.GetBooleanVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetBooleanVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionObjectNameVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetCollectionObjectNameVariable',
            briosa_dot_variables__pb2.GetCollectionObjectNameVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetCollectionObjectNameVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionObjectRefListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetCollectionObjectRefListVariable',
            briosa_dot_variables__pb2.GetCollectionObjectRefListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetCollectionObjectRefListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDoubleVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetDoubleVariable',
            briosa_dot_variables__pb2.GetDoubleVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetDoubleVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntegerVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetIntegerVariable',
            briosa_dot_variables__pb2.GetIntegerVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetIntegerVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNamedDoubleListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetNamedDoubleListVariable',
            briosa_dot_variables__pb2.GetNamedDoubleListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetNamedDoubleListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNamedDoubleListVariableMinMax(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetNamedDoubleListVariableMinMax',
            briosa_dot_variables__pb2.GetNamedDoubleListVariableMinMaxRequest.SerializeToString,
            briosa_dot_variables__pb2.GetNamedDoubleListVariableMinMaxResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPointNameRefListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetPointNameRefListVariable',
            briosa_dot_variables__pb2.GetPointNameRefListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetPointNameRefListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPointNameVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetPointNameVariable',
            briosa_dot_variables__pb2.GetPointNameVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetPointNameVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelationshipRefListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetRelationshipRefListVariable',
            briosa_dot_variables__pb2.GetRelationshipRefListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetRelationshipRefListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReportItemsReferenceListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetReportItemsReferenceListVariable',
            briosa_dot_variables__pb2.GetReportItemsReferenceListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetReportItemsReferenceListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStringRefListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetStringRefListVariable',
            briosa_dot_variables__pb2.GetStringRefListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetStringRefListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStringVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetStringVariable',
            briosa_dot_variables__pb2.GetStringVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetStringVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransformVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetTransformVariable',
            briosa_dot_variables__pb2.GetTransformVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetTransformVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVectorNameRefListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetVectorNameRefListVariable',
            briosa_dot_variables__pb2.GetVectorNameRefListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetVectorNameRefListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVectorVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/GetVectorVariable',
            briosa_dot_variables__pb2.GetVectorVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.GetVectorVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBooleanVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetBooleanVariable',
            briosa_dot_variables__pb2.SetBooleanVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetBooleanVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCollectionObjectNameVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetCollectionObjectNameVariable',
            briosa_dot_variables__pb2.SetCollectionObjectNameVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetCollectionObjectNameVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCollectionObjectRefListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetCollectionObjectRefListVariable',
            briosa_dot_variables__pb2.SetCollectionObjectRefListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetCollectionObjectRefListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDoubleVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetDoubleVariable',
            briosa_dot_variables__pb2.SetDoubleVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetDoubleVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFontVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetFontVariable',
            briosa_dot_variables__pb2.SetFontVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetFontVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetIntegerVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetIntegerVariable',
            briosa_dot_variables__pb2.SetIntegerVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetIntegerVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNamedDoubleListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetNamedDoubleListVariable',
            briosa_dot_variables__pb2.SetNamedDoubleListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetNamedDoubleListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPointNameRefListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetPointNameRefListVariable',
            briosa_dot_variables__pb2.SetPointNameRefListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetPointNameRefListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPointNameVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetPointNameVariable',
            briosa_dot_variables__pb2.SetPointNameVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetPointNameVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRelationshipRefListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetRelationshipRefListVariable',
            briosa_dot_variables__pb2.SetRelationshipRefListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetRelationshipRefListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetReportItemsReferenceListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetReportItemsReferenceListVariable',
            briosa_dot_variables__pb2.SetReportItemsReferenceListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetReportItemsReferenceListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStringRefListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetStringRefListVariable',
            briosa_dot_variables__pb2.SetStringRefListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetStringRefListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStringVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetStringVariable',
            briosa_dot_variables__pb2.SetStringVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetStringVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTransformVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetTransformVariable',
            briosa_dot_variables__pb2.SetTransformVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetTransformVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVectorNameRefListVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetVectorNameRefListVariable',
            briosa_dot_variables__pb2.SetVectorNameRefListVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetVectorNameRefListVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVectorVariable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.Variables/SetVectorVariable',
            briosa_dot_variables__pb2.SetVectorVariableRequest.SerializeToString,
            briosa_dot_variables__pb2.SetVectorVariableResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
