# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from briosa import vector_operations_pb2 as briosa_dot_vector__operations__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in briosa/vector_operations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorOperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddAVectorToVectorNameRefList = channel.unary_unary(
                '/briosa.VectorOperations/AddAVectorToVectorNameRefList',
                request_serializer=briosa_dot_vector__operations__pb2.AddAVectorToVectorNameRefListRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.AddAVectorToVectorNameRefListResult.FromString,
                _registered_method=True)
        self.AutoRangeAndSetVectorGroupColorizationAll = channel.unary_unary(
                '/briosa.VectorOperations/AutoRangeAndSetVectorGroupColorizationAll',
                request_serializer=briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationAllRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationAllResult.FromString,
                _registered_method=True)
        self.AutoRangeAndSetVectorGroupColorizationSelected = channel.unary_unary(
                '/briosa.VectorOperations/AutoRangeAndSetVectorGroupColorizationSelected',
                request_serializer=briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationSelectedRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationSelectedResult.FromString,
                _registered_method=True)
        self.DeleteIthVectorFromVectorGroup = channel.unary_unary(
                '/briosa.VectorOperations/DeleteIthVectorFromVectorGroup',
                request_serializer=briosa_dot_vector__operations__pb2.DeleteIthVectorFromVectorGroupRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.DeleteIthVectorFromVectorGroupResult.FromString,
                _registered_method=True)
        self.DeleteVectorByName = channel.unary_unary(
                '/briosa.VectorOperations/DeleteVectorByName',
                request_serializer=briosa_dot_vector__operations__pb2.DeleteVectorByNameRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.DeleteVectorByNameResult.FromString,
                _registered_method=True)
        self.DeleteVectors = channel.unary_unary(
                '/briosa.VectorOperations/DeleteVectors',
                request_serializer=briosa_dot_vector__operations__pb2.DeleteVectorsRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.DeleteVectorsResult.FromString,
                _registered_method=True)
        self.GetIthVectorFromVectorGroup = channel.unary_unary(
                '/briosa.VectorOperations/GetIthVectorFromVectorGroup',
                request_serializer=briosa_dot_vector__operations__pb2.GetIthVectorFromVectorGroupRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.GetIthVectorFromVectorGroupResult.FromString,
                _registered_method=True)
        self.GetIthVectorFromVectorNameRefList = channel.unary_unary(
                '/briosa.VectorOperations/GetIthVectorFromVectorNameRefList',
                request_serializer=briosa_dot_vector__operations__pb2.GetIthVectorFromVectorNameRefListRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.GetIthVectorFromVectorNameRefListResult.FromString,
                _registered_method=True)
        self.GetNumberOfVectorsInVectorGroup = channel.unary_unary(
                '/briosa.VectorOperations/GetNumberOfVectorsInVectorGroup',
                request_serializer=briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorGroupRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorGroupResult.FromString,
                _registered_method=True)
        self.GetNumberOfVectorsInVectorNameRefList = channel.unary_unary(
                '/briosa.VectorOperations/GetNumberOfVectorsInVectorNameRefList',
                request_serializer=briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorNameRefListRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorNameRefListResult.FromString,
                _registered_method=True)
        self.GetVectorFromVectorGroupByName = channel.unary_unary(
                '/briosa.VectorOperations/GetVectorFromVectorGroupByName',
                request_serializer=briosa_dot_vector__operations__pb2.GetVectorFromVectorGroupByNameRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.GetVectorFromVectorGroupByNameResult.FromString,
                _registered_method=True)
        self.GetVectorGroupProperties = channel.unary_unary(
                '/briosa.VectorOperations/GetVectorGroupProperties',
                request_serializer=briosa_dot_vector__operations__pb2.GetVectorGroupPropertiesRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.GetVectorGroupPropertiesResult.FromString,
                _registered_method=True)
        self.SetVectorGroupColorizationOptionsAll = channel.unary_unary(
                '/briosa.VectorOperations/SetVectorGroupColorizationOptionsAll',
                request_serializer=briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsAllRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsAllResult.FromString,
                _registered_method=True)
        self.SetVectorGroupColorizationOptionsSelected = channel.unary_unary(
                '/briosa.VectorOperations/SetVectorGroupColorizationOptionsSelected',
                request_serializer=briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsSelectedRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsSelectedResult.FromString,
                _registered_method=True)
        self.SortVectors = channel.unary_unary(
                '/briosa.VectorOperations/SortVectors',
                request_serializer=briosa_dot_vector__operations__pb2.SortVectorsRequest.SerializeToString,
                response_deserializer=briosa_dot_vector__operations__pb2.SortVectorsResult.FromString,
                _registered_method=True)


class VectorOperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddAVectorToVectorNameRefList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutoRangeAndSetVectorGroupColorizationAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutoRangeAndSetVectorGroupColorizationSelected(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIthVectorFromVectorGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVectorByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIthVectorFromVectorGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIthVectorFromVectorNameRefList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNumberOfVectorsInVectorGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNumberOfVectorsInVectorNameRefList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVectorFromVectorGroupByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVectorGroupProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVectorGroupColorizationOptionsAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVectorGroupColorizationOptionsSelected(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SortVectors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddAVectorToVectorNameRefList': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAVectorToVectorNameRefList,
                    request_deserializer=briosa_dot_vector__operations__pb2.AddAVectorToVectorNameRefListRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.AddAVectorToVectorNameRefListResult.SerializeToString,
            ),
            'AutoRangeAndSetVectorGroupColorizationAll': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoRangeAndSetVectorGroupColorizationAll,
                    request_deserializer=briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationAllRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationAllResult.SerializeToString,
            ),
            'AutoRangeAndSetVectorGroupColorizationSelected': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoRangeAndSetVectorGroupColorizationSelected,
                    request_deserializer=briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationSelectedRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationSelectedResult.SerializeToString,
            ),
            'DeleteIthVectorFromVectorGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIthVectorFromVectorGroup,
                    request_deserializer=briosa_dot_vector__operations__pb2.DeleteIthVectorFromVectorGroupRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.DeleteIthVectorFromVectorGroupResult.SerializeToString,
            ),
            'DeleteVectorByName': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVectorByName,
                    request_deserializer=briosa_dot_vector__operations__pb2.DeleteVectorByNameRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.DeleteVectorByNameResult.SerializeToString,
            ),
            'DeleteVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVectors,
                    request_deserializer=briosa_dot_vector__operations__pb2.DeleteVectorsRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.DeleteVectorsResult.SerializeToString,
            ),
            'GetIthVectorFromVectorGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIthVectorFromVectorGroup,
                    request_deserializer=briosa_dot_vector__operations__pb2.GetIthVectorFromVectorGroupRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.GetIthVectorFromVectorGroupResult.SerializeToString,
            ),
            'GetIthVectorFromVectorNameRefList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIthVectorFromVectorNameRefList,
                    request_deserializer=briosa_dot_vector__operations__pb2.GetIthVectorFromVectorNameRefListRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.GetIthVectorFromVectorNameRefListResult.SerializeToString,
            ),
            'GetNumberOfVectorsInVectorGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNumberOfVectorsInVectorGroup,
                    request_deserializer=briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorGroupRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorGroupResult.SerializeToString,
            ),
            'GetNumberOfVectorsInVectorNameRefList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNumberOfVectorsInVectorNameRefList,
                    request_deserializer=briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorNameRefListRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorNameRefListResult.SerializeToString,
            ),
            'GetVectorFromVectorGroupByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVectorFromVectorGroupByName,
                    request_deserializer=briosa_dot_vector__operations__pb2.GetVectorFromVectorGroupByNameRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.GetVectorFromVectorGroupByNameResult.SerializeToString,
            ),
            'GetVectorGroupProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVectorGroupProperties,
                    request_deserializer=briosa_dot_vector__operations__pb2.GetVectorGroupPropertiesRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.GetVectorGroupPropertiesResult.SerializeToString,
            ),
            'SetVectorGroupColorizationOptionsAll': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVectorGroupColorizationOptionsAll,
                    request_deserializer=briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsAllRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsAllResult.SerializeToString,
            ),
            'SetVectorGroupColorizationOptionsSelected': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVectorGroupColorizationOptionsSelected,
                    request_deserializer=briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsSelectedRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsSelectedResult.SerializeToString,
            ),
            'SortVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.SortVectors,
                    request_deserializer=briosa_dot_vector__operations__pb2.SortVectorsRequest.FromString,
                    response_serializer=briosa_dot_vector__operations__pb2.SortVectorsResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'briosa.VectorOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('briosa.VectorOperations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorOperations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddAVectorToVectorNameRefList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/AddAVectorToVectorNameRefList',
            briosa_dot_vector__operations__pb2.AddAVectorToVectorNameRefListRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.AddAVectorToVectorNameRefListResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutoRangeAndSetVectorGroupColorizationAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/AutoRangeAndSetVectorGroupColorizationAll',
            briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationAllRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationAllResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutoRangeAndSetVectorGroupColorizationSelected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/AutoRangeAndSetVectorGroupColorizationSelected',
            briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationSelectedRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.AutoRangeAndSetVectorGroupColorizationSelectedResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIthVectorFromVectorGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/DeleteIthVectorFromVectorGroup',
            briosa_dot_vector__operations__pb2.DeleteIthVectorFromVectorGroupRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.DeleteIthVectorFromVectorGroupResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVectorByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/DeleteVectorByName',
            briosa_dot_vector__operations__pb2.DeleteVectorByNameRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.DeleteVectorByNameResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/DeleteVectors',
            briosa_dot_vector__operations__pb2.DeleteVectorsRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.DeleteVectorsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIthVectorFromVectorGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/GetIthVectorFromVectorGroup',
            briosa_dot_vector__operations__pb2.GetIthVectorFromVectorGroupRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.GetIthVectorFromVectorGroupResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIthVectorFromVectorNameRefList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/GetIthVectorFromVectorNameRefList',
            briosa_dot_vector__operations__pb2.GetIthVectorFromVectorNameRefListRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.GetIthVectorFromVectorNameRefListResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNumberOfVectorsInVectorGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/GetNumberOfVectorsInVectorGroup',
            briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorGroupRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorGroupResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNumberOfVectorsInVectorNameRefList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/GetNumberOfVectorsInVectorNameRefList',
            briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorNameRefListRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.GetNumberOfVectorsInVectorNameRefListResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVectorFromVectorGroupByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/GetVectorFromVectorGroupByName',
            briosa_dot_vector__operations__pb2.GetVectorFromVectorGroupByNameRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.GetVectorFromVectorGroupByNameResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVectorGroupProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/GetVectorGroupProperties',
            briosa_dot_vector__operations__pb2.GetVectorGroupPropertiesRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.GetVectorGroupPropertiesResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVectorGroupColorizationOptionsAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/SetVectorGroupColorizationOptionsAll',
            briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsAllRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsAllResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVectorGroupColorizationOptionsSelected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/SetVectorGroupColorizationOptionsSelected',
            briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsSelectedRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.SetVectorGroupColorizationOptionsSelectedResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SortVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.VectorOperations/SortVectors',
            briosa_dot_vector__operations__pb2.SortVectorsRequest.SerializeToString,
            briosa_dot_vector__operations__pb2.SortVectorsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
