# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from briosa import mp_task_overview_pb2 as briosa_dot_mp__task__overview__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in briosa/mp_task_overview_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MpTaskOverviewStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTaskOverviewItem = channel.unary_unary(
                '/briosa.MpTaskOverview/AddTaskOverviewItem',
                request_serializer=briosa_dot_mp__task__overview__pb2.AddTaskOverviewItemRequest.SerializeToString,
                response_deserializer=briosa_dot_mp__task__overview__pb2.AddTaskOverviewItemResult.FromString,
                _registered_method=True)
        self.CreateClearTaskOverviewList = channel.unary_unary(
                '/briosa.MpTaskOverview/CreateClearTaskOverviewList',
                request_serializer=briosa_dot_mp__task__overview__pb2.CreateClearTaskOverviewListRequest.SerializeToString,
                response_deserializer=briosa_dot_mp__task__overview__pb2.CreateClearTaskOverviewListResult.FromString,
                _registered_method=True)
        self.SetCurrentTask = channel.unary_unary(
                '/briosa.MpTaskOverview/SetCurrentTask',
                request_serializer=briosa_dot_mp__task__overview__pb2.SetCurrentTaskRequest.SerializeToString,
                response_deserializer=briosa_dot_mp__task__overview__pb2.SetCurrentTaskResult.FromString,
                _registered_method=True)
        self.SetOverviewImage = channel.unary_unary(
                '/briosa.MpTaskOverview/SetOverviewImage',
                request_serializer=briosa_dot_mp__task__overview__pb2.SetOverviewImageRequest.SerializeToString,
                response_deserializer=briosa_dot_mp__task__overview__pb2.SetOverviewImageResult.FromString,
                _registered_method=True)
        self.SetOverviewTitle = channel.unary_unary(
                '/briosa.MpTaskOverview/SetOverviewTitle',
                request_serializer=briosa_dot_mp__task__overview__pb2.SetOverviewTitleRequest.SerializeToString,
                response_deserializer=briosa_dot_mp__task__overview__pb2.SetOverviewTitleResult.FromString,
                _registered_method=True)
        self.SetTaskItemComment = channel.unary_unary(
                '/briosa.MpTaskOverview/SetTaskItemComment',
                request_serializer=briosa_dot_mp__task__overview__pb2.SetTaskItemCommentRequest.SerializeToString,
                response_deserializer=briosa_dot_mp__task__overview__pb2.SetTaskItemCommentResult.FromString,
                _registered_method=True)
        self.SetTaskItemCompletionValues = channel.unary_unary(
                '/briosa.MpTaskOverview/SetTaskItemCompletionValues',
                request_serializer=briosa_dot_mp__task__overview__pb2.SetTaskItemCompletionValuesRequest.SerializeToString,
                response_deserializer=briosa_dot_mp__task__overview__pb2.SetTaskItemCompletionValuesResult.FromString,
                _registered_method=True)
        self.SetTaskItemName = channel.unary_unary(
                '/briosa.MpTaskOverview/SetTaskItemName',
                request_serializer=briosa_dot_mp__task__overview__pb2.SetTaskItemNameRequest.SerializeToString,
                response_deserializer=briosa_dot_mp__task__overview__pb2.SetTaskItemNameResult.FromString,
                _registered_method=True)
        self.ShowProgressForTaskItem = channel.unary_unary(
                '/briosa.MpTaskOverview/ShowProgressForTaskItem',
                request_serializer=briosa_dot_mp__task__overview__pb2.ShowProgressForTaskItemRequest.SerializeToString,
                response_deserializer=briosa_dot_mp__task__overview__pb2.ShowProgressForTaskItemResult.FromString,
                _registered_method=True)
        self.ShowTaskOverviewList = channel.unary_unary(
                '/briosa.MpTaskOverview/ShowTaskOverviewList',
                request_serializer=briosa_dot_mp__task__overview__pb2.ShowTaskOverviewListRequest.SerializeToString,
                response_deserializer=briosa_dot_mp__task__overview__pb2.ShowTaskOverviewListResult.FromString,
                _registered_method=True)


class MpTaskOverviewServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTaskOverviewItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateClearTaskOverviewList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCurrentTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOverviewImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOverviewTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTaskItemComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTaskItemCompletionValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTaskItemName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowProgressForTaskItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowTaskOverviewList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MpTaskOverviewServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTaskOverviewItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTaskOverviewItem,
                    request_deserializer=briosa_dot_mp__task__overview__pb2.AddTaskOverviewItemRequest.FromString,
                    response_serializer=briosa_dot_mp__task__overview__pb2.AddTaskOverviewItemResult.SerializeToString,
            ),
            'CreateClearTaskOverviewList': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClearTaskOverviewList,
                    request_deserializer=briosa_dot_mp__task__overview__pb2.CreateClearTaskOverviewListRequest.FromString,
                    response_serializer=briosa_dot_mp__task__overview__pb2.CreateClearTaskOverviewListResult.SerializeToString,
            ),
            'SetCurrentTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCurrentTask,
                    request_deserializer=briosa_dot_mp__task__overview__pb2.SetCurrentTaskRequest.FromString,
                    response_serializer=briosa_dot_mp__task__overview__pb2.SetCurrentTaskResult.SerializeToString,
            ),
            'SetOverviewImage': grpc.unary_unary_rpc_method_handler(
                    servicer.SetOverviewImage,
                    request_deserializer=briosa_dot_mp__task__overview__pb2.SetOverviewImageRequest.FromString,
                    response_serializer=briosa_dot_mp__task__overview__pb2.SetOverviewImageResult.SerializeToString,
            ),
            'SetOverviewTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.SetOverviewTitle,
                    request_deserializer=briosa_dot_mp__task__overview__pb2.SetOverviewTitleRequest.FromString,
                    response_serializer=briosa_dot_mp__task__overview__pb2.SetOverviewTitleResult.SerializeToString,
            ),
            'SetTaskItemComment': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTaskItemComment,
                    request_deserializer=briosa_dot_mp__task__overview__pb2.SetTaskItemCommentRequest.FromString,
                    response_serializer=briosa_dot_mp__task__overview__pb2.SetTaskItemCommentResult.SerializeToString,
            ),
            'SetTaskItemCompletionValues': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTaskItemCompletionValues,
                    request_deserializer=briosa_dot_mp__task__overview__pb2.SetTaskItemCompletionValuesRequest.FromString,
                    response_serializer=briosa_dot_mp__task__overview__pb2.SetTaskItemCompletionValuesResult.SerializeToString,
            ),
            'SetTaskItemName': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTaskItemName,
                    request_deserializer=briosa_dot_mp__task__overview__pb2.SetTaskItemNameRequest.FromString,
                    response_serializer=briosa_dot_mp__task__overview__pb2.SetTaskItemNameResult.SerializeToString,
            ),
            'ShowProgressForTaskItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowProgressForTaskItem,
                    request_deserializer=briosa_dot_mp__task__overview__pb2.ShowProgressForTaskItemRequest.FromString,
                    response_serializer=briosa_dot_mp__task__overview__pb2.ShowProgressForTaskItemResult.SerializeToString,
            ),
            'ShowTaskOverviewList': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowTaskOverviewList,
                    request_deserializer=briosa_dot_mp__task__overview__pb2.ShowTaskOverviewListRequest.FromString,
                    response_serializer=briosa_dot_mp__task__overview__pb2.ShowTaskOverviewListResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'briosa.MpTaskOverview', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('briosa.MpTaskOverview', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MpTaskOverview(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTaskOverviewItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.MpTaskOverview/AddTaskOverviewItem',
            briosa_dot_mp__task__overview__pb2.AddTaskOverviewItemRequest.SerializeToString,
            briosa_dot_mp__task__overview__pb2.AddTaskOverviewItemResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateClearTaskOverviewList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.MpTaskOverview/CreateClearTaskOverviewList',
            briosa_dot_mp__task__overview__pb2.CreateClearTaskOverviewListRequest.SerializeToString,
            briosa_dot_mp__task__overview__pb2.CreateClearTaskOverviewListResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCurrentTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.MpTaskOverview/SetCurrentTask',
            briosa_dot_mp__task__overview__pb2.SetCurrentTaskRequest.SerializeToString,
            briosa_dot_mp__task__overview__pb2.SetCurrentTaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetOverviewImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.MpTaskOverview/SetOverviewImage',
            briosa_dot_mp__task__overview__pb2.SetOverviewImageRequest.SerializeToString,
            briosa_dot_mp__task__overview__pb2.SetOverviewImageResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetOverviewTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.MpTaskOverview/SetOverviewTitle',
            briosa_dot_mp__task__overview__pb2.SetOverviewTitleRequest.SerializeToString,
            briosa_dot_mp__task__overview__pb2.SetOverviewTitleResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTaskItemComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.MpTaskOverview/SetTaskItemComment',
            briosa_dot_mp__task__overview__pb2.SetTaskItemCommentRequest.SerializeToString,
            briosa_dot_mp__task__overview__pb2.SetTaskItemCommentResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTaskItemCompletionValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.MpTaskOverview/SetTaskItemCompletionValues',
            briosa_dot_mp__task__overview__pb2.SetTaskItemCompletionValuesRequest.SerializeToString,
            briosa_dot_mp__task__overview__pb2.SetTaskItemCompletionValuesResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTaskItemName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.MpTaskOverview/SetTaskItemName',
            briosa_dot_mp__task__overview__pb2.SetTaskItemNameRequest.SerializeToString,
            briosa_dot_mp__task__overview__pb2.SetTaskItemNameResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowProgressForTaskItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.MpTaskOverview/ShowProgressForTaskItem',
            briosa_dot_mp__task__overview__pb2.ShowProgressForTaskItemRequest.SerializeToString,
            briosa_dot_mp__task__overview__pb2.ShowProgressForTaskItemResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowTaskOverviewList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/briosa.MpTaskOverview/ShowTaskOverviewList',
            briosa_dot_mp__task__overview__pb2.ShowTaskOverviewListRequest.SerializeToString,
            briosa_dot_mp__task__overview__pb2.ShowTaskOverviewListResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
